# Generated by Django 4.1 on 2022-08-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'active'), (1, 'done')], default=0),
        ),
    ]
